#!/bin/bash

# code to generate system info in html format

TITLE='system info for $HOSTNAME'
RIGHTNOW=$(date +"%x %r %Z")
TIME_STAMP='updated on $RIGHTNOW by $USER'

system_info(){

	echo "<h4> System release info </h4>"
	echo "<p> This function is not yet working </p>"
}

home_space(){

	echo "<h4> home directory space for users </h4>"
	echo "<pre>"
		du -s /root/* | sort -nr
	echo "</pre>"

}

drive_space(){

	echo "<h4> Filesystem space </h4>"
	echo "<pre>"
		df 
	echo "</pre>"
}


show_uptime(){

	echo "<h4> System uptime info </h4>"
	echo "<pre>"
		uptime
	echo "</pre>"

}

cat <<- _EOF_

	<html>
		<head>
			<title>
				$TITLE
			</title>

		</head>

		<body>
			<h3> $TITLE </h3>
			<p> $TIME_STAMP </p>
			$(system_info)
			$(show_uptime)
			$(drive_space)
			$(home_space)

		</body>

	</html>
